#line 1 "./src/skins.c"
/*
** Copyright (c) 2009 D. Richard Hipp
**
** This program is free software; you can redistribute it and/or
** modify it under the terms of the Simplified BSD License (also
** known as the "2-Clause License" or "FreeBSD License".)

** This program is distributed in the hope that it will be useful,
** but without any warranty; without even the implied warranty of
** merchantability or fitness for a particular purpose.
**
** Author contact information:
**   drh@hwaci.com
**   http://www.hwaci.com/drh/
**
*******************************************************************************
**
** Implementation of the Setup page for "skins".
*/
#include "config.h"
#include <assert.h>
#include "skins.h"

/* @-comment: ## */
/*
** A black-and-white theme with the project title in a bar across the top
** and no logo image.
*/
static const char zBuiltinSkin1[] =
"REPLACE INTO config(name,mtime,value)\n"
"VALUES('css',now(),'/* General settings for the entire page */\n"
"body {\n"
"  margin: 0ex 1ex;\n"
"  padding: 0px;\n"
"  background-color: white;\n"
"  font-family: sans-serif;\n"
"}\n"
"\n"
"/* The project logo in the upper left-hand corner of each page */\n"
"div.logo {\n"
"  display: table-row;\n"
"  text-align: center;\n"
"  /* vertical-align: bottom;*/\n"
"  font-size: 2em;\n"
"  font-weight: bold;\n"
"  background-color: #707070;\n"
"  color: #ffffff;\n"
"  min-width: 200px;\n"
"  white-space: nowrap;\n"
"}\n"
"\n"
"/* The page title centered at the top of each page */\n"
"div.title {\n"
"  display: table-cell;\n"
"  font-size: 1.5em;\n"
"  font-weight: bold;\n"
"  text-align: center;\n"
"  padding: 0 0 0 10px;\n"
"  color: #404040;\n"
"  vertical-align: bottom;\n"
"  width: 100%;\n"
"}\n"
"\n"
"/* The login status message in the top right-hand corner */\n"
"div.status {\n"
"  display: table-cell;\n"
"  text-align: right;\n"
"  vertical-align: bottom;\n"
"  color: #404040;\n"
"  font-size: 0.8em;\n"
"  font-weight: bold;\n"
"  min-width: 200px;\n"
"  white-space: nowrap;\n"
"}\n"
"\n"
"/* The header across the top of the page */\n"
"div.header {\n"
"  display: table;\n"
"  width: 100%;\n"
"}\n"
"\n"
"/* The main menu bar that appears at the top of the page beneath\n"
"** the header */\n"
"div.mainmenu {\n"
"  padding: 5px 10px 5px 10px;\n"
"  font-size: 0.9em;\n"
"  font-weight: bold;\n"
"  text-align: center;\n"
"  letter-spacing: 1px;\n"
"  background-color: #404040;\n"
"  color: white;\n"
"}\n"
"\n"
"/* The submenu bar that *sometimes* appears below the main menu */\n"
"div.submenu, div.sectionmenu {\n"
"  padding: 3px 10px 3px 0px;\n"
"  font-size: 0.9em;\n"
"  text-align: center;\n"
"  background-color: #606060;\n"
"  color: white;\n"
"}\n"
"div.mainmenu a, div.mainmenu a:visited, div.submenu a, div.submenu a:visited,\n"
"div.sectionmenu>a.button:link, div.sectionmenu>a.button:visited {\n"
"  padding: 3px 10px 3px 10px;\n"
"  color: white;\n"
"  text-decoration: none;\n"
"}\n"
"div.mainmenu a:hover, div.submenu a:hover, div.sectionmenu>a.button:hover {\n"
"  color: #404040;\n"
"  background-color: white;\n"
"}\n"
"\n"
"/* All page content from the bottom of the menu or submenu down to\n"
"** the footer */\n"
"div.content {\n"
"  padding: 0ex 0ex 0ex 0ex;\n"
"}\n"
"/* Hyperlink colors */\n"
"div.content a { color: #604000; }\n"
"div.content a:link { color: #604000;}\n"
"div.content a:visited { color: #600000; }\n"
"\n"
"/* <verbatim> blocks */\n"
"pre.verbatim {\n"
"  background-color: #ffffff;\n"
"  padding: 0.5em;\n"
"  white-space: pre-wrap;\n"
"}\n"
"\n"
"/* Some pages have section dividers */\n"
"div.section {\n"
"  margin-bottom: 0px;\n"
"  margin-top: 1em;\n"
"  padding: 1px 1px 1px 1px;\n"
"  font-size: 1.2em;\n"
"  font-weight: bold;\n"
"  background-color: #404040;\n"
"  color: white;\n"
"  white-space: nowrap;\n"
"}\n"
"\n"
"/* The \"Date\" that occurs on the left hand side of timelines */\n"
"div.divider {\n"
"  background: #a0a0a0;\n"
"  border: 2px #505050 solid;\n"
"  font-size: 1em; font-weight: normal;\n"
"  padding: .25em;\n"
"  margin: .2em 0 .2em 0;\n"
"  float: left;\n"
"  clear: left;\n"
"  white-space: nowrap;\n"
"}\n"
"\n"
"/* The footer at the very bottom of the page */\n"
"div.footer {\n"
"  font-size: 0.8em;\n"
"  margin-top: 12px;\n"
"  padding: 5px 10px 5px 10px;\n"
"  text-align: right;\n"
"  background-color: #404040;\n"
"  color: white;\n"
"}\n"
"\n"
"/* The label/value pairs on (for example) the vinfo page */\n"
"table.label-value th {\n"
"  vertical-align: top;\n"
"  text-align: right;\n"
"  padding: 0.2ex 2ex;\n"
"}');\n"
"REPLACE INTO config(name,mtime,value) VALUES('header',now(),'<html>\n"
"<head>\n"
"<base href=\"$baseurl/$current_page\" />\n"
"<title>$<project_name>: $<title></title>\n"
"<link rel=\"alternate\" type=\"application/rss+xml\" title=\"RSS Feed\"\n"
"      href=\"$home/timeline.rss\">\n"
"<link rel=\"stylesheet\" href=\"$stylesheet_url\" type=\"text/css\"\n"
"      media=\"screen\">\n"
"</head>\n"
"<body>\n"
"<div class=\"header\">\n"
"  <div class=\"title\"><small>$<project_name></small><br />$<title></div>\n"
"  <div class=\"status\"><th1>\n"
"     if {[info exists login]} {\n"
"       puts \"Logged in as $login\"\n"
"     } else {\n"
"       puts \"Not logged in\"\n"
"     }\n"
"  </th1></div>\n"
"</div>\n"
"<div class=\"mainmenu\">\n"
"<th1>\n"
"html \"<a href=''$home$index_page''>Home</a>\\n\"\n"
"if {[anycap jor]} {\n"
"  html \"<a href=''$home/timeline''>Timeline</a>\\n\"\n"
"}\n"
"if {[hascap oh]} {\n"
"  html \"<a href=''$home/tree?ci=tip''>Files</a>\\n\"\n"
"}\n"
"if {[hascap o]} {\n"
"  html \"<a href=''$home/brlist''>Branches</a>\\n\"\n"
"  html \"<a href=''$home/taglist''>Tags</a>\\n\"\n"
"}\n"
"if {[hascap r]} {\n"
"  html \"<a href=''$home/reportlist''>Tickets</a>\\n\"\n"
"}\n"
"if {[hascap j]} {\n"
"  html \"<a href=''$home/wiki''>Wiki</a>\\n\"\n"
"}\n"
"if {[hascap s]} {\n"
"  html \"<a href=''$home/setup''>Admin</a>\\n\"\n"
"} elseif {[hascap a]} {\n"
"  html \"<a href=''$home/setup_ulist''>Users</a>\\n\"\n"
"}\n"
"if {[info exists login]} {\n"
"  html \"<a href=''$home/login''>Logout</a>\\n\"\n"
"} else {\n"
"  html \"<a href=''$home/login''>Login</a>\\n\"\n"
"}\n"
"</th1></div>\n"
"');\n"
"REPLACE INTO config(name,mtime,value)\n"
"VALUES('footer',now(),'<div class=\"footer\">\n"
"Fossil version $manifest_version $manifest_date\n"
"</div>\n"
"</body></html>\n"
"');\n"
;

/*
** A tan theme with the project title above the user identification
** and no logo image.
*/
static const char zBuiltinSkin2[] =
"REPLACE INTO config(name,mtime,value)\n"
"VALUES('css',now(),'/* General settings for the entire page */\n"
"body {\n"
"  margin: 0ex 0ex;\n"
"  padding: 0px;\n"
"  background-color: #fef3bc;\n"
"  font-family: sans-serif;\n"
"}\n"
"\n"
"/* The project logo in the upper left-hand corner of each page */\n"
"div.logo {\n"
"  display: inline;\n"
"  text-align: center;\n"
"  vertical-align: bottom;\n"
"  font-weight: bold;\n"
"  font-size: 2.5em;\n"
"  color: #a09048;\n"
"  white-space: nowrap;\n"
"}\n"
"\n"
"/* The page title centered at the top of each page */\n"
"div.title {\n"
"  display: table-cell;\n"
"  font-size: 2em;\n"
"  font-weight: bold;\n"
"  text-align: left;\n"
"  padding: 0 0 0 5px;\n"
"  color: #a09048;\n"
"  vertical-align: bottom;\n"
"  width: 100%;\n"
"}\n"
"\n"
"/* The login status message in the top right-hand corner */\n"
"div.status {\n"
"  display: table-cell;\n"
"  text-align: right;\n"
"  vertical-align: bottom;\n"
"  color: #a09048;\n"
"  padding: 5px 5px 0 0;\n"
"  font-size: 0.8em;\n"
"  font-weight: bold;\n"
"  white-space: nowrap;\n"
"}\n"
"\n"
"/* The header across the top of the page */\n"
"div.header {\n"
"  display: table;\n"
"  width: 100%;\n"
"}\n"
"\n"
"/* The main menu bar that appears at the top of the page beneath\n"
"** the header */\n"
"div.mainmenu {\n"
"  padding: 5px 10px 5px 10px;\n"
"  font-size: 0.9em;\n"
"  font-weight: bold;\n"
"  text-align: center;\n"
"  letter-spacing: 1px;\n"
"  background-color: #a09048;\n"
"  color: black;\n"
"}\n"
"\n"
"/* The submenu bar that *sometimes* appears below the main menu */\n"
"div.submenu, div.sectionmenu {\n"
"  padding: 3px 10px 3px 0px;\n"
"  font-size: 0.9em;\n"
"  text-align: center;\n"
"  background-color: #c0af58;\n"
"  color: white;\n"
"}\n"
"div.mainmenu a, div.mainmenu a:visited, div.submenu a, div.submenu a:visited,\n"
"div.sectionmenu>a.button:link, div.sectionmenu>a.button:visited {\n"
"  padding: 3px 10px 3px 10px;\n"
"  color: white;\n"
"  text-decoration: none;\n"
"}\n"
"div.mainmenu a:hover, div.submenu a:hover, div.sectionmenu>a.button:hover {\n"
"  color: #a09048;\n"
"  background-color: white;\n"
"}\n"
"\n"
"/* All page content from the bottom of the menu or submenu down to\n"
"** the footer */\n"
"div.content {\n"
"  padding: 1ex 5px;\n"
"}\n"
"div.content a { color: #706532; }\n"
"div.content a:link { color: #706532; }\n"
"div.content a:visited { color: #704032; }\n"
"div.content a:hover { background-color: white; color: #706532; }\n"
"\n"
"/* Some pages have section dividers */\n"
"div.section {\n"
"  margin-bottom: 0px;\n"
"  margin-top: 1em;\n"
"  padding: 3px 3px 0 3px;\n"
"  font-size: 1.2em;\n"
"  font-weight: bold;\n"
"  background-color: #a09048;\n"
"  color: white;\n"
"  white-space: nowrap;\n"
"}\n"
"\n"
"/* The \"Date\" that occurs on the left hand side of timelines */\n"
"div.divider {\n"
"  background: #e1d498;\n"
"  border: 2px #a09048 solid;\n"
"  font-size: 1em; font-weight: normal;\n"
"  padding: .25em;\n"
"  margin: .2em 0 .2em 0;\n"
"  float: left;\n"
"  clear: left;\n"
"  white-space: nowrap;\n"
"}\n"
"\n"
"/* The footer at the very bottom of the page */\n"
"div.footer {\n"
"  font-size: 0.8em;\n"
"  margin-top: 12px;\n"
"  padding: 5px 10px 5px 10px;\n"
"  text-align: right;\n"
"  background-color: #a09048;\n"
"  color: white;\n"
"}\n"
"\n"
"/* Hyperlink colors */\n"
"div.footer a { color: white; }\n"
"div.footer a:link { color: white; }\n"
"div.footer a:visited { color: white; }\n"
"div.footer a:hover { background-color: white; color: #558195; }\n"
"\n"
"/* <verbatim> blocks */\n"
"pre.verbatim {\n"
"  background-color: #f5f5f5;\n"
"  padding: 0.5em;\n"
"  white-space: pre-wrap;\n"
"}\n"
"\n"
"/* The label/value pairs on (for example) the ci page */\n"
"table.label-value th {\n"
"  vertical-align: top;\n"
"  text-align: right;\n"
"  padding: 0.2ex 2ex;\n"
"}');\n"
"REPLACE INTO config(name,mtime,value) VALUES('header',now(),'<html>\n"
"<head>\n"
"<base href=\"$baseurl/$current_page\" />\n"
"<title>$<project_name>: $<title></title>\n"
"<link rel=\"alternate\" type=\"application/rss+xml\" title=\"RSS Feed\"\n"
"      href=\"$home/timeline.rss\">\n"
"<link rel=\"stylesheet\" href=\"$stylesheet_url\" type=\"text/css\"\n"
"      media=\"screen\">\n"
"</head>\n"
"<body>\n"
"<div class=\"header\">\n"
"  <div class=\"title\">$<title></div>\n"
"  <div class=\"status\">\n"
"    <div class=\"logo\">$<project_name></div><br/>\n"
"    <th1>\n"
"     if {[info exists login]} {\n"
"       puts \"Logged in as $login\"\n"
"     } else {\n"
"       puts \"Not logged in\"\n"
"     }\n"
"  </th1></div>\n"
"</div>\n"
"<div class=\"mainmenu\">\n"
"<th1>\n"
"html \"<a href=''$home$index_page''>Home</a>\\n\"\n"
"if {[anycap jor]} {\n"
"  html \"<a href=''$home/timeline''>Timeline</a>\\n\"\n"
"}\n"
"if {[hascap oh]} {\n"
"  html \"<a href=''$home/tree?ci=tip''>Files</a>\\n\"\n"
"}\n"
"if {[hascap o]} {\n"
"  html \"<a href=''$home/brlist''>Branches</a>\\n\"\n"
"  html \"<a href=''$home/taglist''>Tags</a>\\n\"\n"
"}\n"
"if {[hascap r]} {\n"
"  html \"<a href=''$home/reportlist''>Tickets</a>\\n\"\n"
"}\n"
"if {[hascap j]} {\n"
"  html \"<a href=''$home/wiki''>Wiki</a>\\n\"\n"
"}\n"
"if {[hascap s]} {\n"
"  html \"<a href=''$home/setup''>Admin</a>\\n\"\n"
"} elseif {[hascap a]} {\n"
"  html \"<a href=''$home/setup_ulist''>Users</a>\\n\"\n"
"}\n"
"if {[info exists login]} {\n"
"  html \"<a href=''$home/login''>Logout</a>\\n\"\n"
"} else {\n"
"  html \"<a href=''$home/login''>Login</a>\\n\"\n"
"}\n"
"</th1></div>\n"
"');\n"
"REPLACE INTO config(name,mtime,value)\n"
"VALUES('footer',now(),'<div class=\"footer\">\n"
"Fossil version $manifest_version $manifest_date\n"
"</div>\n"
"</body></html>\n"
"');\n"
;

/*
** Black letters on a white or cream background with the main menu
** stuck on the left-hand side.
*/
static const char zBuiltinSkin3[] =
"REPLACE INTO config(name,mtime,value)\n"
"VALUES('css',now(),'/* General settings for the entire page */\n"
"body {\n"
"    margin:0px 0px 0px 0px;\n"
"    padding:0px;\n"
"    font-family:verdana, arial, helvetica, \"sans serif\";\n"
"    color:#333;\n"
"    background-color:white;\n"
"}\n"
"\n"
"/* consistent colours */\n"
"h2 {\n"
"  color: #333;\n"
"}\n"
"h3 {\n"
"  color: #333;\n"
"}\n"
"\n"
"/* The project logo in the upper left-hand corner of each page */\n"
"div.logo {\n"
"  display: table-cell;\n"
"  text-align: left;\n"
"  vertical-align: bottom;\n"
"  font-weight: bold;\n"
"  color: #333;\n"
"  white-space: nowrap;\n"
"}\n"
"\n"
"/* The page title centered at the top of each page */\n"
"div.title {\n"
"  display: table-cell;\n"
"  font-size: 2em;\n"
"  font-weight: bold;\n"
"  text-align: center;\n"
"  color: #333;\n"
"  vertical-align: bottom;\n"
"  width: 100%;\n"
"}\n"
"\n"
"/* The login status message in the top right-hand corner */\n"
"div.status {\n"
"  display: table-cell;\n"
"  padding-right: 10px;\n"
"  text-align: right;\n"
"  vertical-align: bottom;\n"
"  padding-bottom: 5px;\n"
"  color: #333;\n"
"  font-size: 0.8em;\n"
"  font-weight: bold;\n"
"  white-space: nowrap;\n"
"}\n"
"\n"
"/* The header across the top of the page */\n"
"div.header {\n"
"    margin:10px 0px 10px 0px;\n"
"    padding:1px 0px 0px 20px;\n"
"    border-style:solid;\n"
"    border-color:black;\n"
"    border-width:1px 0px;\n"
"    background-color:#eee;\n"
"}\n"
"\n"
"/* The main menu bar that appears at the top left of the page beneath\n"
"** the header. Width must be co-ordinated with the container below */\n"
"div.mainmenu {\n"
"  float: left;\n"
"  margin-left: 10px;\n"
"  margin-right: 10px;\n"
"  font-size: 0.9em;\n"
"  font-weight: bold;\n"
"  padding:5px;\n"
"  background-color:#eee;\n"
"  border:1px solid #999;\n"
"  width:8em;\n"
"}\n"
"\n"
"/* Main menu is now a list */\n"
"div.mainmenu ul {\n"
"  padding: 0;\n"
"  list-style:none;\n"
"}\n"
"div.mainmenu a, div.mainmenu a:visited{\n"
"  padding: 1px 10px 1px 10px;\n"
"  color: #333;\n"
"  text-decoration: none;\n"
"}\n"
"div.mainmenu a:hover {\n"
"  color: #eee;\n"
"  background-color: #333;\n"
"}\n"
"\n"
"/* Container for the sub-menu and content so they don''t spread\n"
"** out underneath the main menu */\n"
"#container {\n"
"  padding-left: 9em;\n"
"}\n"
"\n"
"/* The submenu bar that *sometimes* appears below the main menu */\n"
"div.submenu, div.sectionmenu {\n"
"  padding: 3px 10px 3px 10px;\n"
"  font-size: 0.9em;\n"
"  text-align: center;\n"
"  border:1px solid #999;\n"
"  border-width:1px 0px;\n"
"  background-color: #eee;\n"
"  color: #333;\n"
"}\n"
"div.submenu a, div.submenu a:visited, div.sectionmenu>a.button:link,\n"
"div.sectionmenu>a.button:visited {\n"
"  padding: 3px 10px 3px 10px;\n"
"  color: #333;\n"
"  text-decoration: none;\n"
"}\n"
"div.submenu a:hover, div.sectionmenu>a.button:hover {\n"
"  color: #eee;\n"
"  background-color: #333;\n"
"}\n"
"\n"
"/* All page content from the bottom of the menu or submenu down to\n"
"** the footer */\n"
"div.content {\n"
"  padding: 2ex 1ex 0ex 2ex;\n"
"}\n"
"\n"
"/* Some pages have section dividers */\n"
"div.section {\n"
"  margin-bottom: 0px;\n"
"  margin-top: 1em;\n"
"  padding: 1px 1px 1px 1px;\n"
"  font-size: 1.2em;\n"
"  font-weight: bold;\n"
"  border-style:solid;\n"
"  border-color:#999;\n"
"  border-width:1px 0px;\n"
"  background-color: #eee;\n"
"  color: #333;\n"
"  white-space: nowrap;\n"
"}\n"
"\n"
"/* The \"Date\" that occurs on the left hand side of timelines */\n"
"div.divider {\n"
"  background: #eee;\n"
"  border: 2px #999 solid;\n"
"  font-size: 1em; font-weight: normal;\n"
"  padding: .25em;\n"
"  margin: .2em 0 .2em 0;\n"
"  float: left;\n"
"  clear: left;\n"
"  color: #333;\n"
"  white-space: nowrap;\n"
"}\n"
"\n"
"/* The footer at the very bottom of the page */\n"
"div.footer {\n"
"  font-size: 0.8em;\n"
"  margin-top: 12px;\n"
"  padding: 5px 10px 5px 10px;\n"
"  text-align: right;\n"
"  background-color: #eee;\n"
"  color: #555;\n"
"}\n"
"\n"
"/* <verbatim> blocks */\n"
"pre.verbatim {\n"
"  background-color: #f5f5f5;\n"
"  padding: 0.5em;\n"
"  white-space: pre-wrap;\n"
"}\n"
"\n"
"/* The label/value pairs on (for example) the ci page */\n"
"table.label-value th {\n"
"  vertical-align: top;\n"
"  text-align: right;\n"
"  padding: 0.2ex 2ex;\n"
"}');\n"
"REPLACE INTO config(name,mtime,value) VALUES('header',now(),'<html>\n"
"<head>\n"
"<base href=\"$baseurl/$current_page\" />\n"
"<title>$<project_name>: $<title></title>\n"
"<link rel=\"alternate\" type=\"application/rss+xml\" title=\"RSS Feed\"\n"
"      href=\"$home/timeline.rss\">\n"
"<link rel=\"stylesheet\" href=\"$stylesheet_url\" type=\"text/css\"\n"
"      media=\"screen\">\n"
"</head>\n"
"<body>\n"
"<div class=\"header\">\n"
"  <div class=\"logo\">\n"
"    <img src=\"$logo_image_url\" alt=\"logo\">\n"
"    <br />$<project_name>\n"
"  </div>\n"
"  <div class=\"title\">$<title></div>\n"
"  <div class=\"status\"><th1>\n"
"     if {[info exists login]} {\n"
"       puts \"Logged in as $login\"\n"
"     } else {\n"
"       puts \"Not logged in\"\n"
"     }\n"
"  </th1></div>\n"
"</div>\n"
"<div class=\"mainmenu\">\n"
"<th1>\n"
"html \"<a href=''$home$index_page''>Home</a>\\n\"\n"
"if {[anycap jor]} {\n"
"  html \"<a href=''$home/timeline''>Timeline</a>\\n\"\n"
"}\n"
"if {[hascap oh]} {\n"
"  html \"<a href=''$home/tree?ci=tip''>Files</a>\\n\"\n"
"}\n"
"if {[hascap o]} {\n"
"  html \"<a href=''$home/brlist''>Branches</a>\\n\"\n"
"  html \"<a href=''$home/taglist''>Tags</a>\\n\"\n"
"}\n"
"if {[hascap r]} {\n"
"  html \"<a href=''$home/reportlist''>Tickets</a>\\n\"\n"
"}\n"
"if {[hascap j]} {\n"
"  html \"<a href=''$home/wiki''>Wiki</a>\\n\"\n"
"}\n"
"if {[hascap s]} {\n"
"  html \"<a href=''$home/setup''>Admin</a>\\n\"\n"
"} elseif {[hascap a]} {\n"
"  html \"<a href=''$home/setup_ulist''>Users</a>\\n\"\n"
"}\n"
"if {[info exists login]} {\n"
"  html \"<a href=''$home/login''>Logout</a>\\n\"\n"
"} else {\n"
"  html \"<a href=''$home/login''>Login</a>\\n\"\n"
"}\n"
"</th1></ul></div>\n"
"<div id=\"container\">\n"
"');\n"
"REPLACE INTO config(name,mtime,value) VALUES('footer',now(),'</div>\n"
"<div class=\"footer\">\n"
"Fossil version $manifest_version $manifest_date\n"
"</div>\n"
"</body></html>\n"
"');\n"
;


/*
** Shadow boxes and rounded corners.
*/
static const char zBuiltinSkin4[] =
"REPLACE INTO config(name,mtime,value)\n"
"VALUES('css',now(),'/* General settings for the entire page */\n"
"html {\n"
"  min-height: 100%;\n"
"}\n"
"body {\n"
"  margin: 0ex 1ex;\n"
"  padding: 0px;\n"
"  background-color: white;\n"
"  color: #333;\n"
"  font-family: Verdana, sans-serif;\n"
"  font-size: 0.8em;\n"
"}\n"
"\n"
"/* The project logo in the upper left-hand corner of each page */\n"
"div.logo {\n"
"  display: table-cell;\n"
"  text-align: right;\n"
"  vertical-align: bottom;\n"
"  font-weight: normal;\n"
"  white-space: nowrap;\n"
"}\n"
"\n"
"/* Widths */\n"
"div.header, div.mainmenu, div.submenu, div.content, div.footer {\n"
"  max-width: 900px;\n"
"  margin: auto;\n"
"  padding: 3px 20px 3px 20px;\n"
"  clear: both;\n"
"}\n"
"\n"
"/* The page title at the top of each page */\n"
"div.title {\n"
"  display: table-cell;\n"
"  padding-left: 10px;\n"
"  font-size: 2em;\n"
"  margin: 10px 0 10px -20px;\n"
"  vertical-align: bottom;\n"
"  text-align: left;\n"
"  width: 80%;\n"
"  font-family: Verdana, sans-serif;\n"
"  font-weight: bold;\n"
"  color: #558195;\n"
"  text-shadow: 0px 2px 2px #999999;\n"
"}\n"
"\n"
"/* The login status message in the top right-hand corner */\n"
"div.status {\n"
"  display: table-cell;\n"
"  text-align: right;\n"
"  vertical-align: bottom;\n"
"  color: #333;\n"
"  margin-right: -20px;\n"
"  white-space: nowrap;\n"
"}\n"
"\n"
"/* The main menu bar that appears at the top of the page beneath\n"
" ** the header */\n"
"div.mainmenu {\n"
"  text-align: center;\n"
"  color: white;\n"
"  border-top-left-radius: 5px;\n"
"  border-top-right-radius: 5px;\n"
"  vertical-align: middle;\n"
"  padding-top: 8px;\n"
"  padding-bottom: 8px;\n"
"  background-color: #446979;\n"
"  box-shadow: 0px 3px 4px #333333;\n"
"}\n"
"\n"
"/* The submenu bar that *sometimes* appears below the main menu */\n"
"div.submenu {\n"
"  padding-top:10px;\n"
"  padding-bottom:0;\n"
"  text-align: right;\n"
"  color: #000;\n"
"  background-color: #fff;\n"
"  height: 1.5em;\n"
"  vertical-align:middle;\n"
"  box-shadow: 0px 3px 4px #999;\n"
"}\n"
"div.mainmenu a, div.mainmenu a:visited {\n"
"  padding: 3px 10px 3px 10px;\n"
"  color: white;\n"
"  text-decoration: none;\n"
"}\n"
"div.submenu a, div.submenu a:visited, a.button,\n"
"div.sectionmenu>a.button:link, div.sectinmenu>a.button:visited {\n"
"  padding: 2px 8px;\n"
"  color: #000;\n"
"  font-family: Arial;\n"
"  text-decoration: none;\n"
"  margin:auto;\n"
"  border-radius: 5px;\n"
"  background-color: #e0e0e0;\n"
"  text-shadow: 0px -1px 0px #eee;\n"
"  border: 1px solid #000;\n"
"}\n"
"\n"
"div.mainmenu a:hover {\n"
"  color: #000;\n"
"  background-color: white;\n"
"}\n"
"\n"
"div.submenu a:hover, div.sectionmenu>a.button:hover {\n"
"  background-color: #c0c0c0;\n"
"}\n"
"\n"
"/* All page content from the bottom of the menu or submenu down to\n"
" ** the footer */\n"
"div.content {\n"
"  background-color: #fff;\n"
"  box-shadow: 0px 3px 4px #999;\n"
"  border-bottom-right-radius: 5px;\n"
"  border-bottom-left-radius: 5px;\n"
"  padding-bottom: 1em;\n"
"  min-height:40%;\n"
"}\n"
"\n"
"\n"
"/* Some pages have section dividers */\n"
"div.section {\n"
"  margin-bottom: 0.5em;\n"
"  margin-top: 1em;\n"
"  margin-right: auto;\n"
"  padding: 1px 1px 1px 1px;\n"
"  font-size: 1.2em;\n"
"  font-weight: bold;\n"
"  text-align: center;\n"
"  color: white;\n"
"  border-radius: 5px;\n"
"  background-color: #446979;\n"
"  box-shadow: 0px 3px 4px #333333;\n"
"  white-space: nowrap;\n"
"}\n"
"\n"
"/* The \"Date\" that occurs on the left hand side of timelines */\n"
"div.divider {\n"
"  font-size: 1.2em;\n"
"  font-family: Georgia, serif;\n"
"  font-weight: bold;\n"
"  margin-top: 1em;\n"
"  white-space: nowrap;\n"
"}\n"
"\n"
"/* The footer at the very bottom of the page */\n"
"div.footer {\n"
"  font-size: 0.9em;\n"
"  text-align: right;\n"
"  margin-bottom: 1em;\n"
"  color: #666;\n"
"}\n"
"\n"
"/* Hyperlink colors in the footer */\n"
"div.footer a { color: white; }\n"
"div.footer a:link { color: white; }\n"
"div.footer a:visited { color: white; }\n"
"div.footer a:hover { background-color: white; color: #558195; }\n"
"\n"
"/* <verbatim> blocks */\n"
"pre.verbatim, blockquote pre {\n"
"  font-family: Dejavu Sans Mono, Monaco, Lucida Console, monospace;\n"
"  background-color: #f3f3f3;\n"
"  padding: 0.5em;\n"
"  white-space: pre-wrap;\n"
"}\n"
"\n"
"blockquote pre {\n"
"  border: 1px #000 dashed;\n"
"}\n"
"\n"
"/* The label/value pairs on (for example) the ci page */\n"
"table.label-value th {\n"
"  vertical-align: top;\n"
"  text-align: right;\n"
"  padding: 0.2ex 2ex;\n"
"}\n"
"\n"
"table.report tr th {\n"
"  padding: 3px 5px;\n"
"  text-transform: capitalize;\n"
"  cursor: pointer;\n"
"}\n"
"\n"
"table.report tr td {\n"
"  padding: 3px 5px;\n"
"  cursor: pointer;\n"
"}\n"
"\n"
"textarea {\n"
"  font-size: 1em;\n"
"}');\n"
"REPLACE INTO config(name,mtime,value) VALUES('header',now(),'<html>\n"
"<head>\n"
"<base href=\"$baseurl/$current_page\" />\n"
"<title>$<project_name>: $<title></title>\n"
"<link rel=\"alternate\" type=\"application/rss+xml\" title=\"RSS Feed\"\n"
"      href=\"$home/timeline.rss\">\n"
"<link rel=\"stylesheet\" href=\"$stylesheet_url\" type=\"text/css\"\n"
"      media=\"screen\">\n"
"</head>\n"
"<body>\n"
"<div class=\"header\">\n"
"  <div class=\"logo\">\n"
"    <img src=\"$logo_image_url\" alt=\"logo\">\n"
"    <br />$<project_name>\n"
"  </div>\n"
"  <div class=\"title\">$<title></div>\n"
"  <div class=\"status\"><th1>\n"
"     if {[info exists login]} {\n"
"       puts \"Logged in as $login\"\n"
"     } else {\n"
"       puts \"Not logged in\"\n"
"     }\n"
"  </th1></div>\n"
"</div>\n"
"<div class=\"mainmenu\">\n"
"<th1>\n"
"html \"<a href=''$home$index_page''>Home</a>\\n\"\n"
"if {[anycap jor]} {\n"
"  html \"<a href=''$home/timeline''>Timeline</a>\\n\"\n"
"}\n"
"if {[hascap oh]} {\n"
"  html \"<a href=''$home/tree?ci=tip''>Files</a>\\n\"\n"
"}\n"
"if {[hascap o]} {\n"
"  html \"<a href=''$home/brlist''>Branches</a>\\n\"\n"
"  html \"<a href=''$home/taglist''>Tags</a>\\n\"\n"
"}\n"
"if {[hascap r]} {\n"
"  html \"<a href=''$home/reportlist''>Tickets</a>\\n\"\n"
"}\n"
"if {[hascap j]} {\n"
"  html \"<a href=''$home/wiki''>Wiki</a>\\n\"\n"
"}\n"
"if {[hascap s]} {\n"
"  html \"<a href=''$home/setup''>Admin</a>\\n\"\n"
"} elseif {[hascap a]} {\n"
"  html \"<a href=''$home/setup_ulist''>Users</a>\\n\"\n"
"}\n"
"if {[info exists login]} {\n"
"  html \"<a href=''$home/login''>Logout</a>\\n\"\n"
"} else {\n"
"  html \"<a href=''$home/login''>Login</a>\\n\"\n"
"}\n"
"</th1></div>\n"
"<div id=\"container\">\n"
"');\n"
"REPLACE INTO config(name,mtime,value) VALUES('footer',now(),'</div>\n"
"<div class=\"footer\">\n"
"Fossil version $manifest_version $manifest_date\n"
"</div>\n"
"</body></html>\n"
"');\n"
;


/*
** This skin is intended to be almost identical to the default one, with the
** following changes to the header and footer:
**
** 1. The logo image in the header has been modified to be a hyperlink to the
**    root of the web site containing the repository using the same scheme
**    (i.e. HTTP or HTTPS) as the base URL for the repository.  The header
**    contains a TH1 script block to help accomplish these tasks.
**
** 2. The Fossil version information in the footer has been augmented with
**    hyperlinks to the corresponding points on the timeline in the official
**    Fossil repository.  Additionally, if the Tcl integration feature is
**    enabled, the loaded version of Tcl is included, with a hyperlink to the
**    official Tcl/Tk web site.  The footer also contains a TH1 script block
**    to help accomplish these tasks.
*/
static const char zBuiltinSkin5[] =
"REPLACE INTO config(name,mtime,value)\n"
"VALUES('css',now(),'/* General settings for the entire page */\n"
"body {\n"
"  margin: 0ex 1ex;\n"
"  padding: 0px;\n"
"  background-color: white;\n"
"  font-family: sans-serif;\n"
"}\n"
"\n"
"/* The project logo in the upper left-hand corner of each page */\n"
"div.logo {\n"
"  display: table-cell;\n"
"  text-align: center;\n"
"  vertical-align: bottom;\n"
"  font-weight: bold;\n"
"  color: #558195;\n"
"  min-width: 200px;\n"
"  white-space: nowrap;\n"
"}\n"
"\n"
"/* The page title centered at the top of each page */\n"
"div.title {\n"
"  display: table-cell;\n"
"  font-size: 2em;\n"
"  font-weight: bold;\n"
"  text-align: center;\n"
"  padding: 0 0 0 1em;\n"
"  color: #558195;\n"
"  vertical-align: bottom;\n"
"  width: 100%;\n"
"}\n"
"\n"
"/* The login status message in the top right-hand corner */\n"
"div.status {\n"
"  display: table-cell;\n"
"  text-align: right;\n"
"  vertical-align: bottom;\n"
"  color: #558195;\n"
"  font-size: 0.8em;\n"
"  font-weight: bold;\n"
"  min-width: 200px;\n"
"  white-space: nowrap;\n"
"}\n"
"\n"
"/* The header across the top of the page */\n"
"div.header {\n"
"  display: table;\n"
"  width: 100%;\n"
"}\n"
"\n"
"/* The main menu bar that appears at the top of the page beneath\n"
"** the header */\n"
"div.mainmenu {\n"
"  padding: 5px 10px 5px 10px;\n"
"  font-size: 0.9em;\n"
"  font-weight: bold;\n"
"  text-align: center;\n"
"  letter-spacing: 1px;\n"
"  background-color: #558195;\n"
"  border-top-left-radius: 8px;\n"
"  border-top-right-radius: 8px;\n"
"  color: white;\n"
"}\n"
"\n"
"/* The submenu bar that *sometimes* appears below the main menu */\n"
"div.submenu, div.sectionmenu {\n"
"  padding: 3px 10px 3px 0px;\n"
"  font-size: 0.9em;\n"
"  text-align: center;\n"
"  background-color: #456878;\n"
"  color: white;\n"
"}\n"
"div.mainmenu a, div.mainmenu a:visited, div.submenu a, div.submenu a:visited,\n"
"div.sectionmenu>a.button:link, div.sectionmenu>a.button:visited {\n"
"  padding: 3px 10px 3px 10px;\n"
"  color: white;\n"
"  text-decoration: none;\n"
"}\n"
"div.mainmenu a:hover, div.submenu a:hover, div.sectionmenu>a.button:hover {\n"
"  color: #558195;\n"
"  background-color: white;\n"
"}\n"
"\n"
"/* All page content from the bottom of the menu or submenu down to\n"
"** the footer */\n"
"div.content {\n"
"  padding: 0ex 1ex 1ex 1ex;\n"
"  border: solid #aaa;\n"
"  border-width: 1px;\n"
"}\n"
"\n"
"/* Some pages have section dividers */\n"
"div.section {\n"
"  margin-bottom: 0px;\n"
"  margin-top: 1em;\n"
"  padding: 1px 1px 1px 1px;\n"
"  font-size: 1.2em;\n"
"  font-weight: bold;\n"
"  background-color: #558195;\n"
"  color: white;\n"
"  white-space: nowrap;\n"
"}\n"
"\n"
"/* The \"Date\" that occurs on the left hand side of timelines */\n"
"div.divider {\n"
"  background: #a1c4d4;\n"
"  border: 2px #558195 solid;\n"
"  font-size: 1em; font-weight: normal;\n"
"  padding: .25em;\n"
"  margin: .2em 0 .2em 0;\n"
"  float: left;\n"
"  clear: left;\n"
"  white-space: nowrap;\n"
"}\n"
"\n"
"/* The footer at the very bottom of the page */\n"
"div.footer {\n"
"  clear: both;\n"
"  font-size: 0.8em;\n"
"  padding: 5px 10px 5px 10px;\n"
"  text-align: right;\n"
"  background-color: #558195;\n"
"  border-bottom-left-radius: 8px;\n"
"  border-bottom-right-radius: 8px;\n"
"  color: white;\n"
"}\n"
"\n"
"/* Hyperlink colors in the footer */\n"
"div.footer a { color: white; }\n"
"div.footer a:link { color: white; }\n"
"div.footer a:visited { color: white; }\n"
"div.footer a:hover { background-color: white; color: #558195; }\n"
"\n"
"/* verbatim blocks */\n"
"pre.verbatim {\n"
"  background-color: #f5f5f5;\n"
"  padding: 0.5em;\n"
"  white-space: pre-wrap;\n"
"}\n"
"\n"
"/* The label/value pairs on (for example) the ci page */\n"
"table.label-value th {\n"
"  vertical-align: top;\n"
"  text-align: right;\n"
"  padding: 0.2ex 2ex;\n"
"}');\n"
"REPLACE INTO config(name,mtime,value) VALUES('header',now(),'<html>\n"
"<head>\n"
"<base href=\"$baseurl/$current_page\" />\n"
"<title>$<project_name>: $<title></title>\n"
"<link rel=\"alternate\" type=\"application/rss+xml\" title=\"RSS Feed\"\n"
"      href=\"$home/timeline.rss\" />\n"
"<link rel=\"stylesheet\" href=\"$stylesheet_url\" type=\"text/css\"\n"
"      media=\"screen\" />\n"
"</head>\n"
"<body>\n"
"<div class=\"header\">\n"
"  <div class=\"logo\">\n"
"    <th1>\n"





"    proc getLogoUrl { baseurl } {\n"
"      set idx(first) [string first // $baseurl]\n"
"      if {$idx(first) != -1} {\n"



"        set idx(first+1) [expr {$idx(first) + 2}]\n"










"        set idx(nextRange) [string range $baseurl $idx(first+1) end]\n"
"        set idx(next) [string first / $idx(nextRange)]\n"
"        if {$idx(next) != -1} {\n"





"          set idx(next) [expr {$idx(next) + $idx(first+1)}]\n"



"          set idx(next-1) [expr {$idx(next) - 1}]\n"



"          set scheme [string range $baseurl 0 $idx(first)]\n"
"          set host [string range $baseurl $idx(first+1) $idx(next-1)]\n"



"          if {[string compare $scheme http:/] == 0} {\n"
"            set scheme http://\n"
"          } else {\n"
"            set scheme https://\n"
"          }\n"
"          set logourl $scheme$host/\n"
"        } else {\n"
"          set logourl $baseurl\n"
"        }\n"
"      } else {\n"
"        set logourl $baseurl\n"
"      }\n"
"      return $logourl\n"
"    }\n"
"    set logourl [getLogoUrl $baseurl]\n"
"    </th1>\n"
"    <a href=\"$logourl\">\n"
"      <img src=\"$logo_image_url\" border=\"0\" alt=\"$project_name\">\n"
"    </a>\n"
"  </div>\n"
"  <div class=\"title\"><small>$<project_name></small><br />$<title></div>\n"
"  <div class=\"status\"><th1>\n"
"     if {[info exists login]} {\n"
"       puts \"Logged in as $login\"\n"
"     } else {\n"
"       puts \"Not logged in\"\n"
"     }\n"
"  </th1></div>\n"
"</div>\n"
"<div class=\"mainmenu\">\n"
"<th1>\n"
"html \"<a href=''$home$index_page''>Home</a>\\n\"\n"
"if {[anycap jor]} {\n"
"  html \"<a href=''$home/timeline''>Timeline</a>\\n\"\n"
"}\n"
"if {[hascap oh]} {\n"
"  html \"<a href=''$home/tree?ci=tip''>Files</a>\\n\"\n"
"}\n"
"if {[hascap o]} {\n"
"  html \"<a href=''$home/brlist''>Branches</a>\\n\"\n"
"  html \"<a href=''$home/taglist''>Tags</a>\\n\"\n"
"}\n"
"if {[hascap r]} {\n"
"  html \"<a href=''$home/reportlist''>Tickets</a>\\n\"\n"
"}\n"
"if {[hascap j]} {\n"
"  html \"<a href=''$home/wiki''>Wiki</a>\\n\"\n"
"}\n"
"if {[hascap s]} {\n"
"  html \"<a href=''$home/setup''>Admin</a>\\n\"\n"
"} elseif {[hascap a]} {\n"
"  html \"<a href=''$home/setup_ulist''>Users</a>\\n\"\n"
"}\n"
"if {[info exists login]} {\n"
"  html \"<a href=''$home/login''>Logout</a>\\n\"\n"
"} else {\n"
"  html \"<a href=''$home/login''>Login</a>\\n\"\n"
"}\n"
"</th1></div>\n"
"');\n"
"REPLACE INTO config(name,mtime,value)\n"
"VALUES('footer',now(),'<div class=\"footer\">\n"
"  <th1>\n"
"  proc getTclVersion {} {\n"
"    if {[catch {tclEval info patchlevel} tclVersion] == 0} {\n"
"      return \"<a href=\\\"http://www.tcl.tk/\\\">Tcl</a> version $tclVersion\"\n"
"    }\n"
"    return \"\"\n"
"  }\n"
"  proc getVersion { version } {\n"
"    set length [string length $version]\n"
"    return [string range $version 1 [expr {$length - 2}]]\n"
"  }\n"
"  set version [getVersion $manifest_version]\n"
"  set tclVersion [getTclVersion]\n"
"  set fossilUrl http://www.fossil-scm.org\n"
"  </th1>\n"
"  This page was generated in about\n"
"  <th1>puts [expr {([utime]+[stime]+1000)/1000*0.001}]</th1>s by\n"
"  <a href=\"$fossilUrl/\">Fossil</a>\n"
"  version $release_version $tclVersion\n"
"  <a href=\"$fossilUrl/index.html/info/$version\">$manifest_version</a>\n"
"  <a href=\"$fossilUrl/index.html/timeline?c=$manifest_date&amp;y=ci\">$manifest_date</a>\n"
"</div>\n"
"</body></html>\n"
"');\n"
;

/*
** An array of available built-in skins.
*/
static struct BuiltinSkin {
  const char *zName;
  const char *zValue;
} aBuiltinSkin[] = {
  { "Default",                     0 /* Filled in at runtime */ },
  { "Plain Gray, No Logo",         zBuiltinSkin1                },
  { "Khaki, No Logo",              zBuiltinSkin2                },
  { "Black & White, Menu on Left", zBuiltinSkin3                },
  { "Shadow boxes & Rounded Corners", zBuiltinSkin4             },
  { "Enhanced Default",            zBuiltinSkin5                },
};

/*
** For a skin named zSkinName, compute the name of the CONFIG table
** entry where that skin is stored and return it.
**
** Return NULL if zSkinName is NULL or an empty string.
**
** If ifExists is true, and the named skin does not exist, return NULL.
*/
static char *skinVarName(const char *zSkinName, int ifExists){
  char *z;
  if( zSkinName==0 || zSkinName[0]==0 ) return 0;
  z = mprintf("skin:%s", zSkinName);
  if( ifExists && !db_exists("SELECT 1 FROM config WHERE name=%Q", z) ){
    free(z);
    z = 0;
  }
  return z;
}

/*
** Construct and return a string that represents the current skin if
** useDefault==0 or a string for the default skin if useDefault==1.
**
** Memory to hold the returned string is obtained from malloc.
*/
static char *getSkin(int useDefault){
  Blob val;
  blob_zero(&val);
  blob_appendf(&val,
     "REPLACE INTO config(name,value,mtime) VALUES('css',%Q,now());\n",
     useDefault ? zDefaultCSS : db_get("css", (char*)zDefaultCSS)
  );
  blob_appendf(&val,
     "REPLACE INTO config(name,value,mtime) VALUES('header',%Q,now());\n",
     useDefault ? zDefaultHeader : db_get("header", (char*)zDefaultHeader)
  );
  blob_appendf(&val,
     "REPLACE INTO config(name,value,mtime) VALUES('footer',%Q,now());\n",
     useDefault ? zDefaultFooter : db_get("footer", (char*)zDefaultFooter)
  );
  return blob_str(&val);
}

/*
** Construct the default skin string and fill in the corresponding
** entry in aBuildinSkin[]
*/
static void setDefaultSkin(void){
  aBuiltinSkin[0].zValue = getSkin(1);
}

/*
** WEBPAGE: setup_skin
*/
void setup_skin(void){
  const char *z;
  char *zName;
  char *zErr = 0;
  const char *zCurrent;  /* Current skin */
  int i;                 /* Loop counter */
  Stmt q;

  login_check_credentials();
  if( !g.perm.Setup ){
    login_needed();
  }
  db_begin_transaction();

  /* Process requests to delete a user-defined skin */
  if( P("del1") && (zName = skinVarName(P("sn"), 1))!=0 ){
    style_header("Confirm Custom Skin Delete");
    cgi_printf("<form action=\"%s/setup_skin\" method=\"post\"><div>\n"
           "<p>Deletion of a custom skin is a permanent action that cannot\n"
           "be undone.  Please confirm that this is what you want to do:</p>\n"
           "<input type=\"hidden\" name=\"sn\" value=\"%h\" />\n"
           "<input type=\"submit\" name=\"del2\" value=\"Confirm - Delete The Skin\" />\n"
           "<input type=\"submit\" name=\"cancel\" value=\"Cancel - Do Not Delete\" />\n",(g.zTop),(P("sn")));
    login_insert_csrf_secret();
    cgi_printf("</div></form>\n");
    style_footer();
    return;
  }
  if( P("del2")!=0 && (zName = skinVarName(P("sn"), 1))!=0 ){
    db_multi_exec("DELETE FROM config WHERE name=%Q", zName);
  }

  setDefaultSkin();
  zCurrent = getSkin(0);

  if( P("save")!=0 && (zName = skinVarName(P("save"),0))!=0 ){
    if( db_exists("SELECT 1 FROM config WHERE name=%Q", zName)
          || fossil_strcmp(zName, "Default")==0 ){
      zErr = mprintf("Skin name \"%h\" already exists. "
                     "Choose a different name.", P("sn"));
    }else{
      db_multi_exec("INSERT INTO config(name,value,mtime) VALUES(%Q,%Q,now())",
         zName, zCurrent
      );
    }
  }

  /* The user pressed the "Use This Skin" button. */
  if( P("load") && (z = P("sn"))!=0 && z[0] ){
    int seen = 0;
    for(i=0; i<sizeof(aBuiltinSkin)/sizeof(aBuiltinSkin[0]); i++){
      if( fossil_strcmp(aBuiltinSkin[i].zValue, zCurrent)==0 ){
        seen = 1;
        break;
      }
    }
    if( !seen ){
      seen = db_exists("SELECT 1 FROM config WHERE name GLOB 'skin:*'"
                       " AND value=%Q", zCurrent);
    }
    if( !seen ){
      db_multi_exec(
        "INSERT INTO config(name,value,mtime) VALUES("
        "  strftime('skin:Backup On %%Y-%%m-%%d %%H:%%M:%%S'),"
        "  %Q,now())", zCurrent
      );
    }
    seen = 0;
    for(i=0; i<sizeof(aBuiltinSkin)/sizeof(aBuiltinSkin[0]); i++){
      if( fossil_strcmp(aBuiltinSkin[i].zName, z)==0 ){
        seen = 1;
        zCurrent = aBuiltinSkin[i].zValue;
        db_multi_exec("%s", zCurrent);
        break;
      }
    }
    if( !seen ){
      zName = skinVarName(z,0);
      zCurrent = db_get(zName, 0);
      db_multi_exec("%s", zCurrent);
    }
  }

  style_header("Skins");
  if( zErr ){
    cgi_printf("<p><font color=\"red\">%h</font></p>\n",(zErr));
  }
  cgi_printf("<p>A \"skin\" is a combination of\n"
         "<a href=\"setup_editcss\">CSS</a>,\n"
         "<a href=\"setup_header\">Header</a>,\n"
         "<a href=\"setup_footer\">Footer</a>, and\n"
         "<a href=\"setup_logo\">Logo</a> that determines the look and feel\n"
         "of the web interface.</p>\n"
         "\n"
         "<h2>Available Skins:</h2>\n"
         "<ol>\n");
  for(i=0; i<sizeof(aBuiltinSkin)/sizeof(aBuiltinSkin[0]); i++){
    z = aBuiltinSkin[i].zName;
    if( fossil_strcmp(aBuiltinSkin[i].zValue, zCurrent)==0 ){
      cgi_printf("<li><p>%h.&nbsp;&nbsp; <b>Currently In Use</b></p>\n",(z));
    }else{
      cgi_printf("<li><form action=\"%s/setup_skin\" method=\"post\"><div>\n"
             "%h.&nbsp;&nbsp;\n"
             "<input type=\"hidden\" name=\"sn\" value=\"%h\" />\n"
             "<input type=\"submit\" name=\"load\" value=\"Use This Skin\" />\n"
             "</div></form></li>\n",(g.zTop),(z),(z));
    }
  }
  db_prepare(&q,
     "SELECT substr(name, 6), value FROM config"
     " WHERE name GLOB 'skin:*'"
     " ORDER BY name"
  );
  while( db_step(&q)==SQLITE_ROW ){
    const char *zN = db_column_text(&q, 0);
    const char *zV = db_column_text(&q, 1);
    if( fossil_strcmp(zV, zCurrent)==0 ){
      cgi_printf("<li><p>%h.&nbsp;&nbsp;  <b>Currently In Use</b></p>\n",(zN));
    }else{
      cgi_printf("<li><form action=\"%s/setup_skin\" method=\"post\">\n"
             "%h.&nbsp;&nbsp;\n"
             "<input type=\"hidden\" name=\"sn\" value=\"%h\">\n"
             "<input type=\"submit\" name=\"load\" value=\"Use This Skin\">\n"
             "<input type=\"submit\" name=\"del1\" value=\"Delete This Skin\">\n"
             "</form></li>\n",(g.zTop),(zN),(zN));
    }
  }
  db_finalize(&q);
  cgi_printf("</ol>\n");
  style_footer();
  db_end_transaction(0);
}
